name: my_portfolio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  intl: any
  riverpod_annotation: ^3.0.3
  seo_renderer: ^0.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  generate: true

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/
